[package]
name = "doom-rust-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["cargo", "derive"] }
rand = "0.8.5"
regex = "1.10.3"
sdl2 = "0.36.0"



